### ISSUE TITLE
Link to FlowCloud beta website broken

### ISSUE THREAD

**Issue by Stefan-Schmidt** [CreatorKit/creator-docs#23]
I wanted to follow the Project instructions but failed to at the stage where I needed to create a FlowCloud account to provision the Ci40.

The link to the FlowCloud beta websiite (http://beta.flowm2m.io/) mentioned here:
https://github.com/CreatorKit/creator-docs/blob/dev/creatorkit/Toolbox.md#creating-a-flowm2m-account

is not working.

I tried with a account from the normal FlowCloud website but that one had no way to register a Ci40 and using the code from a Ci20 or Linux registration is failing on my Ci40.

**Comment by abhijit-mahajani-imgtec** [comment]
Sorry @Stefan-Schmidt , we are in the process of moving the creator-docs to https://docs.imgcreator.io/creator/
please use https://beta.imgcreator.io/ for provisioning Ci40 and clickers against the FlowCloud.

>>I tried with a account from the normal FlowCloud website but that one had no way to register a Ci40 and using the code from a Ci20 or Linux registration is failing on my Ci40.
Since the DeviceType for Ci20/Linux are different, that code won't work on Ci40.

we recommend to use https://beta.imgcreator.io/ for provisioning the CreatorKit.

**Comment by Stefan-Schmidt** [comment]
While the docs page works the link for provisioning (https://beta.imgcreator.io/) does not.

I guess I will just be patient and check back next week. :)

**Comment by nikhil-zinjurde-imgtec** [comment]
@Stefan-Schmidt https://beta.imgcreator.io and https://docs.imgcreator.io/creator/ are now live, please create a new account on the website to register your Ci40

**Comment by nikhil-zinjurde-imgtec** [comment]
FlowCloud no longer relevant for Creator projects, hence closing
